version: '3'

services:
  pg:
    image: postgres:14
    environment:
      - POSTGRES_USER=upmeet
      - POSTGRES_PASSWORD=upmeet
      - POSTGRES_DB=upmeet
    ports:
      - "5432:5432"
    volumes:
      - pg-data:/var/lib/postgresql/data
volumes:
  pg-data: {}
  appsmith-stacks: {}